name: CI
on:
  push:
    branches:
    - master

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'auto rebuilding site')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: "master"

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Build
      run: |
        mkdir publish -p
        pushd tests/simple
        make html
        popd
        mv tests/simple/_build/html publish/simple
        pushd tests/fontawesome
        make html
        popd
        mv tests/fontawesome/_build/html publish/fontasewome
        pushd tests/backgroundimage
        make html
        popd
        mv tests/backgroundimage/_build/html publish/backgroundimage
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
