name: CI
on:
  push:
    branches:
    - master

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'auto rebuilding site')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: "master"

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx-sitemap lxml
        pip install -e .
    - name: Build
      env:
        POSTPROCESS: ${{ secrets.POSTPROCESS }}
        ARGS: ${{ secrets.ARGS }}
      run: |
        mkdir publish -p
        pushd tests/simple
        echo "extensions += ['sphinx_sitemap']" >> conf.py
        echo "html_baseurl = 'https://tatsushi-ikeda.github.io/sphinxcontrib-linkattr/simple/'" >> conf.py
        make html
        popd
        mv tests/simple/_build/html publish/simple
        pushd tests/fontawesome
        echo "extensions += ['sphinx_sitemap']" >> conf.py
        echo "html_baseurl = 'https://tatsushi-ikeda.github.io/sphinxcontrib-linkattr/fontawesome/'" >> conf.py
        make html
        popd
        mv tests/fontawesome/_build/html publish/fontawesome
        pushd tests/backgroundimage
        make html
        popd
        mv tests/backgroundimage/_build/html publish/backgroundimage
        echo "extensions += ['sphinx_sitemap']" >> conf.py
        echo "html_baseurl = 'https://tatsushi-ikeda.github.io/sphinxcontrib-linkattr/backgroundimage/'" >> conf.py
        echo "${POSTPROCESS}" > postprocess.py
        echo "${ARGS}" > args
        python3 postprocess.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
        
